spring:
  application:
    name: attendance-system

  datasource:
    url: jdbc:mysql://localhost:3306/attendance_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: "060208"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.example.attendancesystem.entity
  configuration:
    map-underscore-to-camel-case: true

## 本地配置
#file:
#  upload:
#    path: D:/Code_JavaStudy/upload_file/

# 服务器配置
file:
  upload:
    path: /opt/attendance-system/upload_file/

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{15} : %msg%n"